server:
  port: 8001

spring:
  application:
    name: DOCTOR-SERVICE
  config:
    import: "optional:configserver:http://localhost:9000"
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/medicare
      host: localhost
      port: 27017
      database: medicare

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
